import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
Header;
import StoreContextProvider from "./context/StoreContext";
import Header from "@/component/Header/page";
import AuthProviders from "@/Providers/AuthProviders";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProviders>
          <StoreContextProvider>
            <Header />
            <Toaster position="top-right" />
            {children}
          </StoreContextProvider>
        </AuthProviders>
      </body>
    </html>
  );
}
